DROP TABLE blog_posts;

CREATE TABLE blog_posts
(
	id SERIAL4 PRIMARY KEY,
	subject text,
	contents text,
	created_at timestamp default current_timestamp
);

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('At the Earths Core', 'The accompanying roar was all but drowned in Perrys scream of fright, and he came near tumbling headlong into the gaping jaws beneath him, so precipitate was his impetuous haste to vacate the dangerous limb.  It was with a deep sigh of relief that I saw him gain a higher branch in safety. And then the brute did that which froze us both anew with horror. Grasping the trees stem with his powerful paws he dragged down with all the great weight of his huge bulk and all the irresistible force of those mighty muscles.  Slowly, but surely, the stem began to bend toward him.  Inch by inch he worked his paws upward as the tree leaned more and more from the perpendicular.  Perry clung chattering in a panic of terror.  Higher and higher into the bending and swaying tree he clambered.  More and more rapidly was the tree top inclining toward the ground. I saw now why the great brute was armed with such enormous paws.  The use that he was putting them to was precisely that for which nature had intended them.  The sloth-like creature was herbivorous, and to feed that mighty carcass entire trees must be stripped of their foliage. The reason for its attacking us might easily be accounted for on the supposition of an ugly disposition such as that which the fierce and stupid rhinoceros of Africa possesses.  But these were later reflections.  At the moment I was too frantic with apprehension on Perrys behalf to consider aught other than a means to save him from the death that loomed so close. Realizing that I could outdistance the clumsy brute in the open, I dropped from my leafy sanctuary intent only on distracting the things attention from Perry long enough to enable the old man to gain the safety of a larger tree.  There were many close by which not even the terrific strength of that titanic monster could bend. As I touched the ground I snatched a broken limb from the tangled mass that matted the jungle-like floor of the forest and, leaping unnoticed behind the shaggy back, dealt the brute a terrific blow.  My plan worked like magic.  From the previous slowness of the beast I had been led to look for no such marvelous agility', '2006/10/31');

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('A Princess of Mars', 'Close at my heel, in his now accustomed place, followed Woola, the hound, and as I emerged upon the street Sola rushed up to me as though I had been the object of some search on her part.  The cavalcade was returning to the plaza, the homeward march having been given up for that day; nor, in fact, was it recommenced for more than a week, owing to the fear of a return attack by the air craft. Lorquas Ptomel was too astute an old warrior to be caught upon the open plains with a caravan of chariots and children, and so we remained at the deserted city until the danger seemed passed. As Sola and I entered the plaza a sight met my eyes which filled my whole being with a great surge of mingled hope, fear, exultation, and depression, and yet most dominant was a subtle sense of relief and happiness; for just as we neared the throng of Martians I caught a glimpse of the prisoner from the battle craft who was being roughly dragged into a nearby building by a couple of green Martian females. And the sight which met my eyes was that of a slender, girlish figure, similar in every detail to the earthly women of my past life.  She did not see me at first, but just as she was disappearing through the portal of the building which was to be her prison she turned, and her eyes met mine.  Her face was oval and beautiful in the extreme, her every feature was finely chiseled and exquisite, her eyes large and lustrous and her head surmounted by a mass of coal black, waving hair, caught loosely into a strange yet becoming coiffure.  Her skin was of a light reddish copper color, against which the crimson glow of her cheeks and the ruby of her beautifully molded lips shone with a strangely enhancing effect. She was as destitute of clothes as the green Martians who accompanied her; indeed, save for her highly wrought', '2005/03/15');


INSERT INTO blog_posts (subject, contents, created_at) VALUES ('The Wizard of Oz', 'Is the Wicked Witch really destroyed? asked the Voice, and Dorothy thought it trembled a little. Yes, she answered, I melted her with a bucket of water. Dear me, said the Voice, how sudden!  Well, come to me tomorrow, for I must have time to think it over. Youve had plenty of time already, said the Tin Woodman angrily. We shant wait a day longer, said the Scarecrow. You must keep your promises to us! exclaimed Dorothy. The Lion thought it might be as well to frighten the Wizard, so he gave a large, loud roar, which was so fierce and dreadful that Toto jumped away from him in alarm and tipped over the screen that stood in a corner.  As it fell with a crash they looked that way, and the next moment all of them were filled with wonder.  For they saw, standing in just the spot the screen had hidden, a little old man, with a bald head and a wrinkled face, who seemed to be as much surprised as they were. The Tin Woodman, raising his axe, rushed toward the little man and cried out, Who are you? I am Oz, the Great and Terrible, said the little man, in a trembling voice.  But dont strike me--please dont--and Ill do anything you want me to. Our friends looked at him in surprise and dismay. I thought Oz was', '2001/08/23');

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('The War of the Worlds', 'They were described as vast spiderlike machines, nearly a hundred feet high, capable of the speed of an express train, and able to shoot out a beam of intense heat.  Masked batteries, chiefly of field guns, had been planted in the country about Horsell Common, and especially between the Woking district and London.  Five of the machines had been seen moving towards the Thames, and one, by a happy chance, had been destroyed.  In the other cases the shells had missed, and the batteries had been at once annihilated by the Heat-Rays.  Heavy losses of soldiers were mentioned, but the tone of the dispatch was optimistic. The Martians had been repulsed; they were not invulnerable.  They had retreated to their triangle of cylinders again, in the circle about Woking.  Signallers with heliographs were pushing forward upon them from all sides.  Guns were in rapid transit from Windsor, Portsmouth, Aldershot, Woolwich--even from the north; among others, long wire-guns of ninety-five tons from Woolwich.  Altogether one hundred and sixteen were in position or being hastily placed, chiefly covering London.  Never before in England had there been such a vast or rapid concentration of military material. Any further cylinders that fell, it was hoped, could be destroyed at once by high explosives, which were being rapidly manufactured and distributed.  No doubt, ran the report, the situation was of the strangest and gravest description, but the public was exhorted to avoid and discourage panic.  No doubt the Martians were strange', '2007/06/30');


INSERT INTO blog_posts (subject, contents, created_at) VALUES ('Around the World in 80 Days', 'The captain? asked Mr. Fogg. I am the captain. I am Phileas Fogg, of London. And I am Andrew Speedy, of Cardiff. You are going to put to sea? In an hour. You are bound for Bordeaux. And your cargo? No freight.  Going in ballast. Have you any passengers? No passengers.  Never have passengers.  Too much in the way. Is your vessel a swift one? Between eleven and twelve knots.  The Henrietta, well known. Will you carry me and three other persons to Liverpool? To Liverpool?  Why not to China? I said Liverpool. No! No? No.  I am setting out for Bordeaux, and shall go to Bordeaux. Money is no object? None. The captain spoke in a tone which did not admit of a reply. But the owners of the Henrietta resumed Phileas Fogg. The owners are myself, replied the captain.  The vessel belongs to me. I will freight it for you. No. I will buy it of you. No. Phileas Fogg did not betray the least disappointment; but the situation was a grave one.  It was not at New York as at Hong Kong, nor with the captain of the Henrietta as with the captain of the Tankadere.  Up to this time money had smoothed away every obstacle.  Now money failed. Still, some means must be found to cross the Atlantic on a boat, unless by balloonwhich would have been venturesome, besides not being capable of being put in practice.  It seemed that Phileas Fogg had an', '2011/03/21');

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('The Scarlet Plague', 'Here the old man launched into a disquisition on germs and their  natures, using words and phrases of such extraordinary length and  meaninglessness, that the boys grinned at one another and looked out  over the deserted ocean till they forgot the old man was babbling on. But the Scarlet Death, Granser, Edwin at last suggested. Granser recollected himself, and with a start tore himself away from the  rostrum of the lecture-hall, where, to another world audience, he  had been expounding the latest theory, sixty years gone, of germs and  germ-diseases. Yes, yes, Edwin; I had forgotten. Sometimes the memory of the past is  very strong upon me, and I forget that I am a dirty old man, clad in  goat-skin, wandering with my savage grandsons who are goatherds in  the primeval wilderness. The fleeting systems lapse like foam, and so  lapsed our glorious, colossal civilization. I am Granser, a tired old  man. I belong to the tribe of Santa Rosans. I married into that tribe.  My sons and daughters married into the Chauffeurs, the Sacramen-tos, and  the Palo-Altos. You, Hare-Lip, are of the Chauffeurs. You, Edwin, are  of the Sacramentos. And you, Hoo-Hoo, are of the Palo-Altos. Your tribe  takes its name from a town that was near the seat of another great  institution of learning. It was called Stanford University. Yes, I  remember now. It is perfectly clear. I was telling you of the Scarlet  Death. Where was I in my story? You was telling about germs, the things you cant see but which make', '2008/4/07');

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('The Wizard of Oz', 'And I should get no heart, said the Tin Woodman. And I should never get back to Kansas, said Dorothy. We must certainly get to the Emerald City if we can, the Scarecrow continued, and he pushed so hard on his long pole that it stuck fast in the mud at the bottom of the river.  Then, before he could pull it out again--or let go--the raft was swept away, and the poor Scarecrow left clinging to the pole in the middle of the river. Good-bye! he called after them, and they were very sorry to leave him.  Indeed, the Tin Woodman began to cry, but fortunately remembered that he might rust, and so dried his tears on Dorothys apron. Of course this was a bad thing for the Scarecrow. I am now worse off than when I first met Dorothy, he thought.  Then, I was stuck on a pole in a cornfield, where I could make-believe scare the crows, at any rate.  But surely there is no use for a Scarecrow stuck on a pole in the middle of a river.  I am afraid I shall never have any brains, after all! Down the stream the raft floated, and the poor Scarecrow was left far behind.  Then the Lion said: Something must be done to save us.  I think I can swim to the shore and pull the raft after me, if you will only hold fast to the tip of my tail. So he sprang into the water, and the Tin Woodman caught fast hold of his tail.  Then the Lion began to swim with all his might toward the shore.  It was hard work, although he was so big; but by and by they were drawn out of the current, and then Dorothy took the Tin Woodmans long pole and helped push the raft to the land. They were all tired out when they reached the shore at last and stepped off upon the pretty green grass, and they also knew that the stream had carried them a long way past the road of yellow brick that led to the Emerald City. What shall we do now? asked the Tin Woodman, as the Lion', '2007/11/13');

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('Alice in Wonderland', 'No, I didnt, said Alice: I dont think its at all a pity. I said  What for? She boxed the Queens ears; the Rabbit began. Alice gave a little  scream of laughter. Oh, hush! the Rabbit whispered in a frightened  tone. The Queen will hear you! You see, she came rather late, and the  Queen said; Get to your places! shouted the Queen in a voice of thunder, and  people began running about in all directions, tumbling up against each  other; however, they got settled down in a minute or two, and the game  began. Alice thought she had never seen such a curious croquet-ground in  her life; it was all ridges and furrows; the balls were live hedgehogs,  the mallets live flamingoes, and the soldiers had to double themselves  up and to stand on their hands and feet, to make the arches. The chief difficulty Alice found at first was in managing her flamingo:  she succeeded in getting its body tucked away, comfortably enough, under  her arm, with its legs hanging down, but generally, just as she had got  its neck nicely straightened out, and was going to give the hedgehog a  blow with its head, it WOULD twist itself round and look up in her face,  with such a puzzled expression that she could not help bursting out  laughing: and when she had got its head down, and was going to begin  again, it was very provoking to find that the hedgehog had unrolled  itself, and was in the act of crawling away: besides all this, there was  generally a ridge or furrow in the way wherever she wanted to send the  hedgehog to, and, as the doubled-up soldiers were always getting up  and walking off to other parts of the ground, Alice soon came to the  conclusion that it was a very difficult game indeed. The players all played at once without waiting for turns, quarrelling  all the while, and fighting for the hedgehogs; and in a very', '2006/12/20');


