

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('A Terrific Hubbub', 'And I was getting a tattoo during the death from above. And it_s the banner
from the death card that Kilgore is throwing on his victims. I am every
character in between, save for that little weirdo with his guts strapped
in, begging for water. That_s not me.  Yeah. I did. Because he_s nothing
shy of that. And it is his job to go out there and embarrass people.
Embarrass them. Not just beat them, but embarrass them in the process.
Yeah. I did. Because he_s nothing shy of that. And it is his job to go out
there and embarrass people. Embarrass them. Not just beat them, but
embarrass them in the process. I just closed my eyes and in a nanosecond I
cured myself from this ridiculous model of disease, addiction, and
obsession. It_s just ... It_s just the work of sissies.', '2013/08/16');

INSERT INTO blog_posts (subject, contents, created_at) VALUES ('Around the World in 80 Days', 'He did not finish his sentence; for a terrific hubbub now arose on the terrace behind the flight of steps where they stood, and there were frantic shouts of, Hurrah for Mandiboy!  Hip, hip, hurrah! It was a band of voters coming to the rescue of their allies, and taking the Camerfield forces in flank.  Mr. Fogg, Aouda, and Fix found themselves between two fires; it was too late to escape.  The torrent of men, armed with loaded canes and sticks, was irresistible.  Phileas Fogg and Fix were roughly hustled in their attempts to protect their fair companion; the former, as cool as ever, tried to defend himself with the weapons which nature has placed at the end of every Englishmans arm, but in vain.  A big brawny fellow with a red beard, flushed face, and broad shoulders, who seemed to be the chief of the band, raised his clenched fist to strike Mr. Fogg, whom he would have given a crushing blow, had not Fix rushed in and received it in', '2011/03/21');
INSERT INTO blog_posts (subject, contents, created_at) VALUES ('The Scarlet Plague', 'On his back was a quiverful of arrows. From a sheath hanging about his  neck on a thong, projected the battered handle of a hunting knife. He  was as brown as a berry, and walked softly, with almost a catlike tread.  In marked contrast with his sunburned skin were his eyes; blue, deep  blue, but keen and sharp as a pair of gimlets. They seemed to bore into  aft about him in a way that was habitual. As he went along he smelled  things, as well, his distended, quivering nostrils carrying to his brain  an endless series of messages from the outside world. Also, his hearing  was acute, and had been so trained that it operated automatically.  Without conscious effort, he heard all the slight sounds in the apparent  quiet; heard, and differentiated, and classified these sounds; whether  they were of the wind rustling the leaves, of the humming of bees and  gnats, of the distant rumble of the sea that drifted to him only in  lulls, or of the gopher, just under his foot, shoving a pouchful of  earth into the entrance of his hole. Suddenly he became alertly tense. Sound, sight, and odor had given him  a simultaneous warning. His hand went back to the old man, touching  him, and the pair stood still. Ahead, at one side of the top of the  embankment, arose a crackling sound, and the boy_s gaze', '2008/4/07');
INSERT INTO blog_posts (subject, contents, created_at) VALUES ('The Wizard of Oz', 'They came from all directions, and there were thousands of them: big mice and little mice and middle-sized mice; and each one brought a piece of string in his mouth.  It was about this time that Dorothy woke from her long sleep and opened her eyes.  She was greatly astonished to find herself lying upon the grass, with thousands of mice standing around and looking at her timidly.  But the Scarecrow told her about everything, and turning to the dignified little Mouse, he said: Permit me to introduce to you her Majesty, the Queen. Dorothy nodded gravely and the Queen made a curtsy, after which she became quite friendly with the little girl. The Scarecrow and the Woodman now began to fasten the mice to the truck, using the strings they had brought.  One end of a string was tied around the neck of each mouse and the other end to the truck.  Of course the truck was a thousand times bigger than any of the', '2007/11/13');
INSERT INTO blog_posts (subject, contents, created_at) VALUES ('Alice in Wonderland', 'I havent the least idea what youre talking about, said Alice. Ive tried the roots of trees, and Ive tried banks, and Ive tried  hedges, the Pigeon went on, without attending to her; but those  serpents! Theres no pleasing them! Alice was more and more puzzled, but she thought there was no use in  saying anything more till the Pigeon had finished. As if it wasnt trouble enough hatching the eggs, said the Pigeon;  but I must be on the look-out for serpents night and day! Why, I  havent had a wink of sleep these three weeks! Im very sorry youve been annoyed, said Alice, who was beginning to  see its meaning. And just as Id taken the highest tree in the wood, continued the  Pigeon, raising its voice to a shriek, and just as I was thinking I  should be free of them at last, they must needs come wriggling down from  the sky! Ugh, Serpent! But Im NOT a serpent, I tell you! said Alice. Im a; Im a;  Well! WHAT are you? said the Pigeon. I can see youre trying to ', '2006/12/20');


